export interface Project {
  id: string;
  name: string;
  description: string;
  descriptionEn?: string;
  techStack: string[];
  highlight: string;
  url?: string;
  repoUrl?: string;
  featured?: boolean;
  status?: 'workInProgress' | 'discontinued' | 'experimental' | 'completed';
  image?: string;
  images?: string[];
  showInDonate?: boolean;
}

export const projects: Project[] = [
  {
    id: "windows-xp-online",
    name: "Windows XP Online",
    description: "• Built browser-based OS simulation with real-time multi-user sync (WebSockets)\n• Implemented window manager and state synchronization layer\n• Recreated classic UI with multitasking, draggable windows, themes and sounds",
    techStack: ["React", "TypeScript", "WebSockets"],
    highlight: "Faithful Windows XP recreation in browser with WebSockets multiplayer",
    url: "https://w-xp-online.web.app/",
    repoUrl: "https://github.com/LucasHenriqueDiniz/windowx-xp-online",
    featured: true,
    status: "experimental",
    image: "/projects/windows_xp_online.webp",
  },
  {
    id: "weeb-profile",
    name: "Weeb Profile",
    description: "• Built dynamic SVG generation system with multi-API integration (Last.fm, MyAnimeList, GitHub)\n• Automated data pipeline via GitHub Actions for real-time collection and rendering\n• Implemented GitHub profile README widgets with live statistics",
    techStack: ["Node.js", "TypeScript", "API Integration", "Automation"],
    highlight: "Dynamic SVG generation with multi-API integration and GitHub Actions pipeline",
    url: "https://weeb-profile-web-client.vercel.app/",
    repoUrl: "https://github.com/LucasHenriqueDiniz/WeebProfile",
    featured: true,
    status: "workInProgress",
    image: "/projects/weebprofile.webp",
    showInDonate: true,
  },
  {
    id: "heartopia-guide",
    name: "Heartopia Guide",
    description: "• Built production-grade content platform with Next.js App Router and dynamic routing\n• Implemented structured content ingestion and SEO-focused architecture\n• Designed caching strategies for data-driven pages",
    techStack: ["Next.js", "TypeScript", "SEO", "App Router"],
    highlight: "Production-grade content platform with SEO-focused architecture",
    url: "https://heartopia.guide/en",
    repoUrl: "https://github.com/LucasHenriqueDiniz/heartopia-guide",
    featured: true,
    status: "completed",
    image: "/projects/heartopiaguide.webp",
    showInDonate: true,
    images: [
      "/projects/heartopiaguide.webp",
      "/projects/heartopia-guide-2.webp",
      "/projects/heartopia-guide-3.webp",
      "/projects/heartopia-guide-4.webp",
    ],
  },
  {
    id: "include-gurias",
    name: "Include Gurias",
    description: "• Built fullstack institutional platform with custom headless CMS\n• Implemented authentication system and admin dashboard with full CRUD\n• Designed Supabase RLS policies and strategic caching layer",
    techStack: ["Next.js", "TypeScript", "Supabase", "PostgreSQL"],
    highlight: "Fullstack institutional platform with custom headless CMS",
    url: "https://www.includegurias.com.br",
    repoUrl: "https://github.com/include-gurias/includegurias-website",
    featured: true,
    status: "completed",
    image: "/projects/include-gurias.webp",
    images: [
      "/projects/include-gurias.webp",
      "/projects/include-gurias-2.webp",
      "/projects/include-gurias-3.webp",
    ],
  },
  {
    id: "botschannel",
    name: "BotsChannel",
    description: "• Built serverless SaaS for multi-channel chatbot automation (WhatsApp, Telegram, Instagram)\n• Architected microservices with AWS Lambda and async message processing\n• Integrated third-party messaging APIs with custom webhook handlers",
    techStack: ["Node.js", "TypeScript", "AWS Lambda", "PostgreSQL", "API Integration"],
    highlight: "Serverless SaaS for multi-channel chatbot automation with AWS Lambda",
    url: "https://platform.botschannel.com/en",
    repoUrl: "https://github.com/BotsChannel",
    featured: true,
    status: "discontinued",
    image: "/projects/bots-channel.webp",
    images: [
      "/projects/bots-channel.webp",
      "/projects/bots-channel-2.webp",
    ],
  },
  {
    id: "resgate-rs",
    name: "Resgate RS",
    description: "• Built missing people registration platform in response to RS tragedy\n• Implemented real-time search and registration with Next.js and Supabase\n• Open-sourced project for community emergency response coordination",
    techStack: ["Next.js", "TypeScript", "Supabase"],
    highlight: "Missing people registration platform built for RS tragedy response",
    url: "https://resgate-rs.vercel.app",
    repoUrl: "https://github.com/BotsChannel/resgate-rs",
    featured: true,
    status: "completed",
    image: "/projects/resgate-rs.webp",
    images: [
      "/projects/resgate-rs.webp",
      "/projects/resgate-rs-2.webp",
    ],
  },
  {
    id: "autowabba",
    name: "AutoWabba",
    description: "• Built desktop automation app for bulk downloads via Playwright\n• Implemented parallel request processing with intelligent retry system\n• Designed Electron architecture with IPC for state management",
    techStack: ["Electron", "Node.js", "Playwright", "Automation"],
    highlight: "Desktop automation for bulk downloads with Playwright and Electron",
    url: "https://github.com/LucasHenriqueDiniz/AutoWabba",
    repoUrl: "https://github.com/LucasHenriqueDiniz/AutoWabba",
    featured: true,
    status: "completed",
    image: "/projects/autowabba.webp",
  },
  {
    id: "itemmarketcap",
    name: "ItemMarketCap",
    description: "• Built real-time Steam market analytics with multi-API integration\n• Implemented data collection and normalization pipeline\n• Designed Redis caching system for aggregated metrics processing",
    techStack: ["Next.js", "TypeScript", "API Integration", "Redis", "Data Processing"],
    highlight: "Real-time Steam market analytics with Redis caching",
    url: "https://item-marketcap.vercel.app/",
    repoUrl: "https://github.com/LucasHenriqueDiniz/item-marketcap",
    featured: true,
    status: "workInProgress",
    image: "/projects/itemmarketcap.webp",
    images: [
      "/projects/itemmarketcap.webp",
      "/projects/item-market-cap-2.webp",
      "/projects/item-market-cap-3.webp",
    ],
  },
  {
    id: "comunica-mulher",
    name: "ComunicaMulher",
    description: "• Built complaint management system with moderation workflow\n• Implemented intake pipeline with validation and data sanitization\n• Designed granular Supabase RLS policies and admin dashboard with filters",
    techStack: ["Next.js", "TypeScript", "Supabase", "PostgreSQL"],
    highlight: "Complaint management system with moderation workflow",
    url: "https://reclame-mulher.vercel.app/",
    repoUrl: "https://github.com/LucasHenriqueDiniz/reclame-mulher",
    featured: true,
    status: "workInProgress",
    image: "/projects/comunicamulher.webp",
    images: [
      "/projects/comunicamulher.webp",
      "/projects/comunica-mulher-2.webp",
      "/projects/comunica-mulher-3.webp",
    ],
  },
  {
    id: "quizhub",
    name: "QuizHub",
    description: "• Built quiz platform with real-time ranking and collaborative editor\n• Implemented question ingestion pipeline with LLM-assisted processing\n• Designed complex relational data modeling with PostgreSQL",
    techStack: ["Next.js", "TypeScript", "Supabase", "PostgreSQL", "LLM Integration"],
    highlight: "Quiz platform with real-time ranking and LLM-assisted processing",
    url: "https://quizhub.com.br/",
    repoUrl: "https://github.com/LucasHenriqueDiniz/quizhub",
    featured: true,
    status: "workInProgress",
    image: "/projects/quizhub-thumbnail.webp",
    images: [
      "/projects/quizhub-thumbnail.webp",
      "/projects/quizhub.webp",
      "/projects/quizhub-2.webp",
      "/projects/quizhub-3.webp",
    ],
  },
  {
    id: "context-tools",
    name: "Context Tools",
    description: "• Built VS Code extension for LLM-friendly context copying\n• Implemented file, selection, and project tree extraction\n• Generated formatted blocks optimized for LLMs and issue trackers",
    techStack: ["TypeScript", "VS Code", "Extension"],
    highlight: "VS Code extension for LLM-friendly context copying",
    url: "https://marketplace.visualstudio.com/items?itemName=lucashenriquediniz.vscode-context-tools",
    repoUrl: "https://github.com/LucasHenriqueDiniz/vscode-context-tools",
    status: "completed",
    image: "/projects/contexttools.webp",
    showInDonate: true,
  },
  {
    id: "mannco-enhancer",
    name: "Mannco Enhancer",
    description: "• Built browser extension for enhanced trading experience on Mannco.store\n• Implemented UI overlays, price tracking and inventory shortcuts\n• Published to Chrome Web Store with auto-update pipeline",
    techStack: ["TypeScript", "Browser Extension", "Chrome API"],
    highlight: "Browser extension enhancing Team Fortress 2 trading platform",
    url: "https://github.com/LucasHenriqueDiniz/mannco-enhancer",
    repoUrl: "https://github.com/LucasHenriqueDiniz/mannco-enhancer",
    status: "completed",
    image: "/projects/mannco-enhancer.webp",
    showInDonate: true,
  },
  {
    id: "instagram-enhancer",
    name: "Instagram Enhancer",
    description: "• Built browser extension for Instagram power users\n• Added bulk download, story analytics and UI customization features\n• Implemented content script injection with performance-first architecture",
    techStack: ["TypeScript", "Browser Extension", "Chrome API"],
    highlight: "Browser extension adding advanced features to Instagram",
    repoUrl: "https://github.com/LucasHenriqueDiniz/instagram-enhancer",
    status: "completed",
    image: "/projects/instagram-enhancer.webp",
    showInDonate: true,
  },
  {
    id: "hypixel-daily-skip",
    name: "Hypixel Daily Skip",
    description: "• Built automation tool for Hypixel daily reward claiming\n• Implemented headless browser flow with session persistence\n• Designed scheduling system with retry logic and notification hooks",
    techStack: ["Node.js", "Automation", "Puppeteer"],
    highlight: "Automation tool for Hypixel Minecraft server daily rewards",
    repoUrl: "https://github.com/LucasHenriqueDiniz/hypixel-daily-skip",
    status: "completed",
    image: "/projects/hypixel-auto-join.webp",
  },
  {
    id: "basicao-workshop",
    name: "Basicão Workshop",
    description: "• Built educational platform for programming fundamentals workshops\n• Implemented interactive lessons with live code execution\n• Designed progress tracking and certificate generation system",
    techStack: ["Next.js", "TypeScript", "Supabase"],
    highlight: "Educational platform for hands-on programming workshops",
    url: "https://basicao-workshop.vercel.app/",
    repoUrl: "https://github.com/LucasHenriqueDiniz/basicao-workshop",
    status: "workInProgress",
    image: "/projects/basicao-workshop.webp",
  },
  {
    id: "clearcut",
    name: "ClearCut",
    description: "• Built video clipping and sharing tool with precise timestamp controls\n• Implemented canvas-based preview rendering and export pipeline\n• Designed shareable link system with embedded player",
    techStack: ["React", "TypeScript", "Canvas API", "FFmpeg"],
    highlight: "Video clipping tool with precise controls and shareable exports",
    repoUrl: "https://github.com/LucasHenriqueDiniz/clearcut",
    status: "experimental",
    image: "/projects/clearcut.webp",
  },
];

export const featuredProjects = projects.filter(p => p.featured).slice(0, 9);
