export interface Project {
  id: string;
  name: string;
  description: string;
  descriptionEn?: string;
  techStack: string[];
  highlight: string;
  url?: string;
  repoUrl?: string;
  featured?: boolean;
  status?: 'workInProgress' | 'discontinued' | 'experimental' | 'completed';
  image?: string;
}

export const projects: Project[] = [
  {
    id: "windows-xp-online",
    name: "Windows XP Online",
    description: "A faithful Windows XP recreation in the browser, featuring multitasking, draggable windows, classic themes, sounds, and even games. Real-time for multiple users via WebSockets and React.",
    techStack: ["React", "TypeScript", "WebSockets"],
    highlight: "Faithful Windows XP recreation in browser with WebSockets multiplayer",
    url: "https://w-xp-online.web.app/",
    repoUrl: "https://github.com/LucasHenriqueDiniz/windowx-xp-online",
    featured: true,
    status: "experimental",
    image: "/projects/windows-xp-online.webp",
  },
  {
    id: "weeb-profile",
    name: "Weeb Profile",
    description: "Dynamic SVG generation system for GitHub with multi-API integration (Last.fm, MyAnimeList, GitHub). Automated pipeline via GitHub Actions for real-time data collection, processing, and rendering.",
    techStack: ["Node.js", "TypeScript", "API Integration", "Automation"],
    highlight: "Dynamic SVG generation with multi-API integration and GitHub Actions pipeline",
    url: "https://weeb-profile-web-client.vercel.app/",
    repoUrl: "https://github.com/LucasHenriqueDiniz/WeebProfile",
    featured: true,
    status: "workInProgress",
    image: "/projects/weeb-profile.webp",
  },
  {
    id: "heartopia-guide",
    name: "Heartopia Guide",
    description: "Production-grade content platform using Next.js (App Router) with dynamic routing and data-driven pages. Structured content ingestion, caching strategies and SEO-focused architecture.",
    techStack: ["Next.js", "TypeScript", "SEO", "App Router"],
    highlight: "Production-grade content platform with SEO-focused architecture",
    url: "https://heartopia.guide/en",
    repoUrl: "https://github.com/LucasHenriqueDiniz/heartopia-guide",
    featured: true,
    status: "completed",
    image: "/projects/heartopia-guide.webp",
  },
  {
    id: "include-gurias",
    name: "Include Gurias",
    description: "Fullstack institutional platform with custom headless CMS. Authentication system, admin dashboard with full CRUD, and content pipeline with validations. Supabase RLS policies and strategic caching.",
    techStack: ["Next.js", "TypeScript", "Supabase", "PostgreSQL"],
    highlight: "Fullstack institutional platform with custom headless CMS",
    url: "https://www.includegurias.com.br",
    repoUrl: "https://github.com/include-gurias/includegurias-website",
    featured: true,
    status: "completed",
    image: "/projects/include-gurias.webp",
  },
  {
    id: "botschannel-platform",
    name: "BotsChannel Platform",
    description: "Serverless SaaS platform for multi-channel chatbot automation. Microservices architecture with AWS Lambda, asynchronous message processing, and integration with WhatsApp, Telegram, and Instagram APIs.",
    techStack: ["Node.js", "TypeScript", "AWS Lambda", "PostgreSQL", "API Integration"],
    highlight: "Serverless SaaS for multi-channel chatbot automation with AWS Lambda",
    url: "https://platform.botschannel.com/en",
    repoUrl: "https://github.com/BotsChannel",
    featured: true,
    status: "discontinued",
    image: "/projects/botschannel.webp",
  },
  {
    id: "resgate-rs",
    name: "Resgate RS",
    description: "Platform created in response to the RS tragedy for registering and searching missing people. Uses Next.js, Supabase, and PostgreSQL. Open source out of respect for the victims.",
    techStack: ["Next.js", "TypeScript", "Supabase"],
    highlight: "Missing people registration platform built for RS tragedy response",
    url: "https://resgate-rs.vercel.app",
    repoUrl: "https://github.com/BotsChannel/resgate-rs",
    featured: true,
    status: "completed",
    image: "/projects/resgate-rs.webp",
  },
  {
    id: "autowabba",
    name: "AutoWabba",
    description: "Desktop automation application for bulk downloads via Playwright. Browser automation, state management, and parallel request processing. Electron architecture with IPC and intelligent retry system.",
    techStack: ["Electron", "Node.js", "Playwright", "Automation"],
    highlight: "Desktop automation for bulk downloads with Playwright and Electron",
    url: "https://github.com/LucasHenriqueDiniz/AutoWabba",
    repoUrl: "https://github.com/LucasHenriqueDiniz/AutoWabba",
    featured: true,
    status: "completed",
    image: "/projects/autowabba.webp",
  },
  {
    id: "itemmarketcap",
    name: "ItemMarketCap",
    description: "Real-time analytics platform with multi-API Steam integration. Market data collection and normalization pipeline, Redis caching system, and aggregated metrics processing.",
    techStack: ["Next.js", "TypeScript", "API Integration", "Redis", "Data Processing"],
    highlight: "Real-time Steam market analytics with Redis caching",
    url: "https://item-marketcap.vercel.app/",
    repoUrl: "https://github.com/LucasHenriqueDiniz/item-marketcap",
    featured: true,
    status: "workInProgress",
    image: "/projects/itemmarketcap.webp",
  },
  {
    id: "comunica-mulher",
    name: "ComunicaMulher",
    description: "Complaint management system with moderation workflow and validations. Intake pipeline with data sanitization, granular Supabase RLS policies, and admin dashboard with advanced filters.",
    techStack: ["Next.js", "TypeScript", "Supabase", "PostgreSQL"],
    highlight: "Complaint management system with moderation workflow",
    url: "https://reclame-mulher.vercel.app/",
    repoUrl: "https://github.com/LucasHenriqueDiniz/reclame-mulher",
    featured: true,
    status: "workInProgress",
    image: "/projects/comunica-mulher.webp",
  },
  {
    id: "quizhub",
    name: "QuizHub",
    description: "Quiz platform with real-time ranking system and collaborative editor. Question ingestion pipeline with LLM-assisted processing. Complex relational data modeling with PostgreSQL.",
    techStack: ["Next.js", "TypeScript", "Supabase", "PostgreSQL", "LLM Integration"],
    highlight: "Quiz platform with real-time ranking and LLM-assisted processing",
    url: "https://quizhub.com.br/",
    repoUrl: "https://github.com/LucasHenriqueDiniz/quizhub",
    featured: true,
    status: "workInProgress",
    image: "/projects/quizhub.webp",
  },
  {
    id: "context-tools",
    name: "Context Tools",
    description: "VS Code extension that copies files, selections, project tree, and diagnostics into formatted blocks optimized for sharing with LLMs and issue trackers.",
    techStack: ["TypeScript", "VS Code", "Extension"],
    highlight: "VS Code extension for LLM-friendly context copying",
    url: "https://marketplace.visualstudio.com/items?itemName=lucashenriquediniz.vscode-context-tools",
    repoUrl: "https://github.com/LucasHenriqueDiniz/vscode-context-tools",
    status: "completed",
    image: "/projects/context-tools.webp",
  },
  {
    id: "siot-web-flasher",
    name: "SIOT Web Flasher",
    description: "Flash firmware and monitor serial of ESP32/ESP8266 directly from the browser. Supports Web Serial API, modern UI, and Electron desktop integration. Essential tool for makers and IoT.",
    techStack: ["TypeScript", "Electron", "Web Serial"],
    highlight: "Web-based ESP32/ESP8266 firmware flasher with serial monitoring",
    url: "https://siot-web-flasher.vercel.app/",
    repoUrl: "https://github.com/LucasHenriqueDiniz/siot-web-flasher",
    status: "completed",
    image: "/projects/siot-web-flasher.webp",
  },
];

export const featuredProjects = projects.filter(p => p.featured).slice(0, 9);
